In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib
import sys
print(sys.executable)

c:\Users\hp\anaconda\python.exe

In [2]:
import pandas as pd
df=pd.read_csv("dataset.csv")
print(df.head())

   Age  Annual_Income  Monthly_Salary  Loan_Amount Credit_History  \
0   25         400000           33333       100000           Good
1   30         600000           50000       150000           Good
2   35         300000           25000       250000           Poor
3   28         500000           41667       120000           Good
4   40         700000           58333       300000           Good

   Existing_Loans    Debt Employment_Status Loan_Status
0               1   50000          Employed        Good
1               2   70000          Employed        Good
2               3  150000     Self-Employed         Bad
3               1   40000          Employed        Good
4               2  100000          Business        Good

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                20 non-null     int64
 1   Annual_Income      20 non-null     int64
 2   Monthly_Salary     20 non-null     int64
 3   Loan_Amount        20 non-null     int64
 4   Credit_History     20 non-null     object
 5   Existing_Loans     20 non-null     int64
 6   Debt               20 non-null     int64
 7   Employment_Status  20 non-null     object
 8   Loan_Status        20 non-null     object
dtypes: int64(6), object(3)
memory usage: 1.5+ KB

In [4]:
df.isnull().sum()

Age                  0
Annual_Income        0
Monthly_Salary       0
Loan_Amount          0
Credit_History       0
Existing_Loans       0
Debt                 0
Employment_Status    0
Loan_Status          0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

df.head()

,Age,Annual_Income,Monthly_Salary,Loan_Amount,Credit_History,Existing_Loans,Debt,Employment_Status,Loan_Status
0,25,400000,33333,100000,0,1,50000,1,1
1,30,600000,50000,150000,0,2,70000,1,1
2,35,300000,25000,250000,1,3,150000,2,0
3,28,500000,41667,120000,0,1,40000,1,1
4,40,700000,58333,300000,0,2,100000,0,1

In [6]:
import pandas as pd

df = pd.read_csv("dataset.csv")
df.head()

,Age,Annual_Income,Monthly_Salary,Loan_Amount,Credit_History,Existing_Loans,Debt,Employment_Status,Loan_Status
0,25,400000,33333,100000,Good,1,50000,Employed,Good
1,30,600000,50000,150000,Good,2,70000,Employed,Good
2,35,300000,25000,250000,Poor,3,150000,Self-Employed,Bad
3,28,500000,41667,120000,Good,1,40000,Employed,Good
4,40,700000,58333,300000,Good,2,100000,Business,Good

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ["Credit_History", "Employment_Status", "Loan_Status"]:
    df[col] = le.fit_transform(df[col])

df.head()

,Age,Annual_Income,Monthly_Salary,Loan_Amount,Credit_History,Existing_Loans,Debt,Employment_Status,Loan_Status
0,25,400000,33333,100000,0,1,50000,1,1
1,30,600000,50000,150000,0,2,70000,1,1
2,35,300000,25000,250000,1,3,150000,2,0
3,28,500000,41667,120000,0,1,40000,1,1
4,40,700000,58333,300000,0,2,100000,0,1

In [8]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

print(X.head())
print(y.head())

   Age  Annual_Income  Monthly_Salary  Loan_Amount  Credit_History  \
0   25         400000           33333       100000               0
1   30         600000           50000       150000               0
2   35         300000           25000       250000               1
3   28         500000           41667       120000               0
4   40         700000           58333       300000               0

   Existing_Loans    Debt  Employment_Status
0               1   50000                  1
1               2   70000                  1
2               3  150000                  2
3               1   40000                  1
4               2  100000                  0
0    1
1    1
2    0
3    1
4    1
Name: Loan_Status, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
print(X.dtypes)

Age                  int64
Annual_Income        int64
Monthly_Salary       int64
Loan_Amount          int64
Credit_History       int64
Existing_Loans       int64
Debt                 int64
Employment_Status    int64
dtype: object

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Credit_History"] = le.fit_transform(df["Credit_History"])
df["Employment_Status"] = le.fit_transform(df["Employment_Status"])
df["Loan_Status"] = le.fit_transform(df["Loan_Status"])

In [12]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [14]:
print(X.dtypes)

Age                  int64
Annual_Income        int64
Monthly_Salary       int64
Loan_Amount          int64
Credit_History       int64
Existing_Loans       int64
Debt                 int64
Employment_Status    int64
dtype: object

In [15]:
print(X.head())

   Age  Annual_Income  Monthly_Salary  Loan_Amount  Credit_History  \
0   25         400000           33333       100000               0
1   30         600000           50000       150000               0
2   35         300000           25000       250000               1
3   28         500000           41667       120000               0
4   40         700000           58333       300000               0

   Existing_Loans    Debt  Employment_Status
0               1   50000                  1
1               2   70000                  1
2               3  150000                  2
3               1   40000                  1
4               2  100000                  0

In [16]:
X = df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [18]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [19]:
y_pred = model.predict(X_test)
print(y_pred)

[1 0 0 1]

In [20]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [21]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2 0]
 [0 2]]

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

In [23]:
import joblib
joblib.dump(model,"model.pkl")
print("Model Saved Successfully")

Model Saved Successfully